---
- name: Delete {{ prov_nic }} due to modify nmcli bug
  nmcli: 
    conn_name: "{{ prov_nic }}"
    type: ethernet
    state: absent
    
- name: Create Bridge labeled provisioning
  nmcli:
    conn_name: provisioning
    type: bridge
    ifname: provisioning
    autoconnect: yes
    stp: off
    ip4: 172.22.0.1/24
    state: present

- name: Create Bridge slave on {{ prov_nic }}
  nmcli:
    conn_name: "{{ prov_nic }}"
    type: bridge-slave
    hairpin: no
    ip4_method: manual
    ifname: "{{ prov_nic }}"
    master: provisioning
    autoconnect: yes
    state: present
    
- name: Create Bridge labeled baremetal
  nmcli:
    conn_name: baremetal
    type: bridge
    ifname: baremetal
    autoconnect: yes
    stp: off
    state: present

- name: Create Bridge slave on {{ pub_nic }}
  nmcli:
    conn_name: "{{ pub_nic }}"
    type: bridge-slave
    hairpin: no
    ifname: "{{ pub_nic }}"
    master: baremetal
    autoconnect: yes
    state: present

- name: Modify the Bridge slave file
  template:
    src: roles/node-prep/templates/pub_nic.j2
    dest: "/etc/sysconfig/network-scripts/ifcfg-{{ pub_nic }}"
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Register the UUID of {{ pub_nic }}
  shell: |
    nmcli c show | grep {{ pub_nic }} | awk '{ print $2 }' | grep -v {{ pub_nic }}
  register: uuid

- name: Add UUID line to ifcfg-{{pub_nic}} file
  lineinfile: 
    path: "/etc/sysconfig/network-scripts/ifcfg-{{ pub_nic }}"
    insertafter: '^#BRIDGE=baremetal '
    line: "UUID={{ uuid.stdout }}"

- name: Get DHCP for baremetal bridge
  shell: |
    /usr/sbin/ifdown {{ pub_nic }}; /usr/bin/pkill dhclient ; /usr/sbin/ifdown baremetal ; /usr/sbin/ifup {{ pub_nic }}; /usr/sbin/ifup baremetal
